
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://llrmbyafcffporpjtbka.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxscm1ieWFmY2ZmcG9ycGp0YmthIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA0ODQ0NDMsImV4cCI6MjA1NjA2MDQ0M30.ShMOZeaBC3DNCKbIcFIbWOgE02327Lup6mHndxDfios";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY, 
  {
    auth: {
      persistSession: true,
      autoRefreshToken: true,
      storage: localStorage
    },
    realtime: {
      params: {
        eventsPerSecond: 10
      }
    }
  }
);

// Enable realtime messages on the `messages` table with better logging
supabase.channel('custom-all-channel')
  .on(
    'postgres_changes',
    { event: '*', schema: 'public', table: 'messages' },
    (payload) => {
      console.log('Message received via realtime!', payload);
      // Dispatch a custom event that our components can listen for
      const event = new CustomEvent('new-message', { detail: payload });
      window.dispatchEvent(event);
    }
  )
  .subscribe((status) => {
    console.log('Realtime subscription status:', status);
  });

// Add a helper function for marking messages as read
export const markMessagesAsRead = async (conversationId: string, userId: string) => {
  if (!conversationId || !userId) return { error: 'Missing required parameters' };
  
  return await supabase
    .from('messages')
    .update({ is_read: true })
    .eq('conversation_id', conversationId)
    .eq('receiver_id', userId);
};

// Add a helper function for sending messages
export const sendMessage = async (message: {
  content: string;
  conversation_id: string;
  sender_id: string;
  receiver_id: string;
}) => {
  return await supabase
    .from('messages')
    .insert([message])
    .select('*');
};

// Add a helper function for fetching conversations
export const fetchUserConversations = async (userId: string) => {
  if (!userId) return { data: null, error: 'No user ID provided' };
  
  return await supabase
    .from('conversations')
    .select(`
      *,
      participants:conversations_participants (
        user_id,
        user:profiles (*)
      ),
      last_message:messages (*)
    `)
    .contains('participants', [{ user_id: userId }])
    .order('updated_at', { ascending: false });
};

